name: feature_mind_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  dio: ^5.5.0+1
  get_storage: ^2.1.1
  intl: ^0.19.0
  logger: ^2.3.0
  fade_shimmer: ^2.2.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  envied: ^0.5.4+1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/logo_ios.png
  color_dark: "#151715"
  image_dark: assets/png/logo_ios.png
  android_12:
    image: assets/png/logo12.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    image_dark: assets/png/logo12.png
    color_dark: "#151715"
    icon_background_color_dark: "#151715"

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
